- name: Get joyent image uuid from name
  command: imgadm avail -j name={{ image_name }} type=zone-dataset
  register: imgadm_raw
  when: image_uuid is not defined and brand == "joyent"
 
- name: Get linux image uuid from name
  command: imgadm avail -j name={{ image_name }} type=lx-dataset
  register: imgadm_raw_name
  when: image_uuid is not defined and brand == "lx"

- name: Get linux kernel version from uuid
  command: imgadm avail -j uuid={{ image_uuid }} type=lx-dataset
  register: imgadm_raw_uuid
  when: image_uuid is defined and brand == "lx"

- name: Parse imgadm (by name) output
  set_fact: imgadm_clean="{{ imgadm_raw_name.stdout|from_json }}"
  when: image_uuid is not defined and brand == "lx"

- name: Parse imgadm (by uuid) output
  set_fact: imgadm_clean="{{ imgadm_raw_uuid.stdout|from_json }}"
  when: image_uuid is defined and brand == "lx"

- name: Set image vars from imgadm output
  set_fact:
    image_uuid: "{{ imgadm_clean[-1]['manifest']['uuid'] }}"
    kernel_version: "{{ imgadm_clean[-1]['manifest']['tags']['kernel_version'] }}"
  when: image_uuid is not defined
 
- name: Importing image uuid
  command: imgadm import {{ image_uuid }}
